### ISSUE TITLE
Clarify term "dataverse" vs. "dataverse collection"

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/repo4cat#1]
Do I understand it correctly, there is

- *dataverse* - the repository software
- *dataverse collection* - A folder-like data structure made to group data sets and (optionally) other dataverse collections.

The key point is that there is only one datastructure `dataverse collection` and the current readme just uses a short form `dataverse` when it really means `dataverse collection`. Is this correct?

In the [dataverse docs](https://guides.dataverse.org/en/latest/user/dataverse-management.html) both terms (`dataverse` and `dataverse collection`) are used for apparently the same thing, too. Using consistent language would be helpful for a precise understanding.

**Comment by vkush** [comment]
Also related here commit https://github.com/nfdi4cat/repo4cat/commit/cd39d772b65f7f7a4ec11b7c5c6a5ab7cc43debd.
