### ISSUE TITLE
API for harvesting metadata from repo4cat to meta4cat

### ISSUE THREAD

**Issue by sefeoglu** [nfdi4cat/repo4cat#24]
Hello, 

I would like to harvest metadata from your repository to our meta portal (https://meta4cat.fokus.fraunhofer.de/datasets?locale=en).
Do you have any API to access metadata on your repo4cat?

Thanks in advance.
Best,

**Comment by vkush** [comment]
Dear @sefeoglu,
Many thanks for your request! The OAI server is already activated. Here you can find the most important information:
- info about Dataverse configuration: https://guides.dataverse.org/en/latest/admin/harvestserver.html
- examples of OAI-PMH requests: 
  - https://support.datacite.org/docs/datacite-oai-pmh
  - https://www.openarchives.org/OAI/openarchivesprotocol.html

Just to test I have used such commands:

```
# 1. Test OAI-PMH with some requests
#    -> https://support.datacite.org/docs/datacite-oai-pmh
#
SERVER_URL=https://YOUR_DATAVERSE_INSTANCE

# 1.1 Get info about OAI-Server (identify)
#
curl -X GET $SERVER_URL/oai?verb=Identify | less

# 1.2 List all supported metadata formats
#     -> http://www.openarchives.org/OAI/openarchivesprotocol.html#ListMetadataFormats
#
curl -X GET $SERVER_URL/oai?verb=ListMetadataFormats

# 1.3 List all available records
#     -> http://www.openarchives.org/OAI/openarchivesprotocol.html#ListRecords
#
curl -X GET "$SERVER_URL/oai?verb=ListRecords&metadataPrefix=oai_dc"
curl -X GET "$SERVER_URL/oai?verb=ListRecords&metadataPrefix=dataverse_json"

```

**Comment by sefeoglu** [comment]
Thanks for the information :) . This helps a lot.

Best,
