### ISSUE TITLE
[info] Handle identifiers visible even for unvisible datasets/files

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/repo4cat#30]
This is to inform about a dataverse limitation reported by "our" @vkush in https://github.com/IQSS/dataverse/issues/8881

Since the URLs in the handle record do not disclose any information about the dataverse/organisation/dataset/file via the url-scheme the visiblity of the handle should be no problem. 

For example, see this handle record for a file 

https://hdl.handle.net/21.11165/4Cat/a48r-4u58/1?noredirect=true

It does not contain any information about the resource it links to.

**Comment by dalito** [comment]
@vkush - maybe we need another tag to identify upstream issues (in dataverse) that we can/will not solve ourselves like this one.

**Comment by vkush** [comment]
"external" tag is created.

**Comment by vkush** [comment]
The issue will be solved in 6.11! See the link to the original Dataverse issue in the description above.
